angle_enable_swiftshader=false
angle_has_histograms=false
build_dawn_tests=false
chrome_pgo_phase=0
clang_use_chrome_plugins=false
dawn_use_swiftshader=false
disable_fieldtrial_testing_config=true
enable_hangout_services_extension=false
enable_mdns=false
enable_perfetto_unittests=false
enable_remoting=false
enable_reporting=false
enable_service_discovery=false
enable_swiftshader=false
enable_swiftshader_vulkan=false
enable_vr=false
enable_widevine=true
exclude_unwind_tables=true
google_api_key=""
google_default_client_id=""
google_default_client_secret=""
is_cfi=true
safe_browsing_mode=0
safe_browsing_use_unrar=false
treat_warnings_as_errors=false
use_cfi_cast=true
use_official_google_api_keys=false
use_unofficial_version_number=false
use_webgpu_on_vulkan_via_gl_interop=false
v8_enable_drumbrake=true
